clone_depth: 1
version: '{build}'
skip_non_tags: true
image: Visual Studio 2017
configuration: Release
before_build:
  - cmd: nuget sources add -name osu-framework-native -Source https://ci.appveyor.com/nuget/osu-framework-nativedeps/api/v2/package
  - cmd: nuget sources
  - cmd: nuget restore osu-framework.sln
  - cmd: nuget restore osu-framework.iOS.sln
build_script:
  - ps: if($env:appveyor_repo_tag -eq 'True') { Update-AppveyorBuild -Version $env:appveyor_repo_tag_name }
  - dotnet pack osu.Framework /p:Version=%APPVEYOR_BUILD_VERSION% /p:GenerateDocumentationFile=true
  - cmd: msbuild /t:pack osu.Framework.iOS /p:Configuration=Release /p:Version=%APPVEYOR_BUILD_VERSION%
artifacts:
  - path: osu.Framework/bin/Release/*.nupkg
  - path: osu.Framework.iOS/bin/Release/*.nupkg
deploy:
  - provider: Environment
    name: nuget
  - provider: Environment
    name: github